### ISSUE TITLE
无法访问，本地需要代理吗？

### ISSUE THREAD

**Issue by lurenlym** [slippersheepig/chatgpt-html#11] opened 2023-02-20 09:01 UTC
![Image_20230220170111](https://user-images.githubusercontent.com/26338549/220060047-2ecff1f6-f5cc-4c55-b2f3-f2b526d3a538.png)

**Comment by slippersheepig** [comment] 2023-02-20 09:17
看起来像是config.json缺少账号信息

**Comment by lurenlym** [comment] 2023-02-20 09:25
> 
有的，config.json填了确认正常的邮箱账及号密码

**Comment by slippersheepig** [comment] 2023-02-20 09:28
那估计是作者的代理服务端临时故障了，最后说的是连接被忽略了，连不上的话应该不是这种提示

**Comment by slippersheepig** [comment] 2023-02-21 05:10
due to this problem not caused by my project, close this issue.
you can create an issue to find answer [here](https://github.com/acheong08/ChatGPT/issues)

**Closed by slippersheepig** 2023-02-21 05:10 UTC
